import React from 'react';
import { View, Text, ScrollView, TouchableOpacity, StyleSheet } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { theme } from '../constants/theme';

const LAST_UPDATED = 'June 7, 2026';

export default function PrivacyPolicyScreen() {
  const router = useRouter();

  return (
    <SafeAreaView style={styles.safe} edges={['top']}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
          <Ionicons name="arrow-back" size={20} color={theme.colors.textPrimary} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Privacy Policy</Text>
        <View style={{ width: 40 }} />
      </View>

      <ScrollView contentContainerStyle={styles.content}>
        <Text style={styles.updated}>Last updated: {LAST_UPDATED}</Text>

        <Section title="1. Who We Are">
          Whyrl ("we", "us", "our") is a news aggregation application that uses artificial intelligence to summarize trending topics. Our contact email is support@whyrl.online.
        </Section>

        <Section title="2. What Data We Collect">
          <Bullet>Email address — collected when you create an account, used solely for authentication via Supabase.</Bullet>
          <Bullet>Usage data — anonymous analytics on which categories and regions you view, to improve content relevance.</Bullet>
          <Bullet>Purchase data — subscription status managed by RevenueCat. We do not store payment card details.</Bullet>
          <Bullet>Device identifiers — collected by Google AdMob for ad serving. See Section 5 for details.</Bullet>
        </Section>

        <Section title="3. How We Use Your Data">
          <Bullet>To authenticate you and maintain your session.</Bullet>
          <Bullet>To remember your preferences (categories, region, saved cards) across devices.</Bullet>
          <Bullet>To manage your premium subscription status.</Bullet>
          <Bullet>To serve relevant advertisements to free-tier users.</Bullet>
          We do not sell your personal data to third parties.
        </Section>

        <Section title="4. Content & AI Summaries">
          Whyrl aggregates publicly available trending topics from NewsAPI and Reddit. All summaries and details displayed in the app are generated by Claude AI (Anthropic) and do not reproduce original article text. We do not store or redistribute original publisher content. Attribution to the originating source (NewsAPI or Reddit) is shown on each card.
        </Section>

        <Section title="5. Advertising (Google AdMob)">
          Free-tier users see ads served by Google AdMob. AdMob may collect device identifiers and usage data to personalize ads. On iOS, we request your permission before enabling personalized advertising via Apple's App Tracking Transparency framework. You may opt out at any time in your device Settings → Privacy → Tracking. Premium subscribers see no ads.
        </Section>

        <Section title="6. Third-Party Services">
          <Bullet>Supabase — authentication and user data storage (supabase.com/privacy)</Bullet>
          <Bullet>RevenueCat — subscription management (revenuecat.com/privacy)</Bullet>
          <Bullet>Google AdMob — advertising (policies.google.com/privacy)</Bullet>
          <Bullet>Anthropic Claude — AI summarization (anthropic.com/privacy)</Bullet>
          <Bullet>NewsAPI — news headlines (newsapi.org/privacy)</Bullet>
        </Section>

        <Section title="7. Data Retention">
          Your account data is retained for as long as your account is active. You may request deletion at any time via Settings → Delete Account. We will delete your personal data within 30 days of such a request.
        </Section>

        <Section title="8. Your Rights (Canadian Users)">
          Under Canada's Personal Information Protection and Electronic Documents Act (PIPEDA), you have the right to access, correct, and request deletion of your personal data. To exercise these rights, contact us at support@whyrl.online.
        </Section>

        <Section title="9. Children's Privacy">
          Whyrl is not directed at children under 13. We do not knowingly collect personal data from children. If you believe a child has provided us with personal data, contact us immediately.
        </Section>

        <Section title="10. Changes to This Policy">
          We may update this policy from time to time. We will notify you of material changes via in-app notice. Continued use of Whyrl after changes constitutes acceptance of the updated policy.
        </Section>

        <Section title="11. Contact">
          For privacy inquiries: support@whyrl.online
        </Section>
      </ScrollView>
    </SafeAreaView>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <View style={styles.section}>
      <Text style={styles.sectionTitle}>{title}</Text>
      <Text style={styles.sectionBody}>{children}</Text>
    </View>
  );
}

function Bullet({ children }: { children: React.ReactNode }) {
  return <Text style={styles.bullet}>{'• '}{children}{'\n'}</Text>;
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: theme.colors.bg },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.surfaceBorder,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    color: theme.colors.textPrimary,
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  content: {
    padding: 20,
    paddingBottom: 60,
    maxWidth: 680,
    alignSelf: 'center',
    width: '100%',
  },
  updated: {
    color: theme.colors.textMuted,
    fontSize: 12,
    marginBottom: 24,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    color: theme.colors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 8,
  },
  sectionBody: {
    color: theme.colors.textSecondary,
    fontSize: 14,
    lineHeight: 22,
  },
  bullet: {
    color: theme.colors.textSecondary,
    fontSize: 14,
    lineHeight: 22,
  },
});
