import React from 'react';
import { View, Text, ScrollView, TouchableOpacity, StyleSheet } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { theme } from '../constants/theme';

const LAST_UPDATED = 'June 7, 2026';

export default function TermsScreen() {
  const router = useRouter();

  return (
    <SafeAreaView style={styles.safe} edges={['top']}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
          <Ionicons name="arrow-back" size={20} color={theme.colors.textPrimary} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Terms of Service</Text>
        <View style={{ width: 40 }} />
      </View>

      <ScrollView contentContainerStyle={styles.content}>
        <Text style={styles.updated}>Last updated: {LAST_UPDATED}</Text>

        <Section title="1. Acceptance of Terms">
          By downloading, installing, or using Whyrl, you agree to be bound by these Terms of Service. If you do not agree, do not use the app. These terms are governed by the laws of Canada.
        </Section>

        <Section title="2. Description of Service">
          Whyrl is an AI-powered news aggregation application. We collect publicly available trending topics from third-party sources (NewsAPI, Reddit) and use Claude AI (Anthropic) to generate original summaries. We do not reproduce or redistribute original news articles. Whyrl is not a news publisher and does not claim editorial responsibility for underlying source content.
        </Section>

        <Section title="3. User Accounts">
          <Bullet>You must provide a valid email address to create an account.</Bullet>
          <Bullet>You are responsible for maintaining the confidentiality of your password.</Bullet>
          <Bullet>You must be at least 13 years old to use Whyrl.</Bullet>
          <Bullet>You may not create accounts on behalf of others without their permission.</Bullet>
          We reserve the right to suspend or terminate accounts that violate these terms.
        </Section>

        <Section title="4. Subscriptions and Billing">
          Whyrl offers a free tier (with ads) and a premium subscription (ad-free). Subscriptions are billed through the Apple App Store and managed by RevenueCat.{'\n\n'}
          <Bullet>Subscriptions renew automatically unless cancelled at least 24 hours before the renewal date.</Bullet>
          <Bullet>To cancel, manage your subscription in your Apple ID account settings.</Bullet>
          <Bullet>No refunds are provided for partial subscription periods, except where required by law.</Bullet>
        </Section>

        <Section title="5. AI-Generated Content Disclaimer">
          All summaries and trend analyses displayed in Whyrl are generated by artificial intelligence and are provided for informational purposes only. This content:{'\n\n'}
          <Bullet>May contain inaccuracies or errors.</Bullet>
          <Bullet>Does not constitute professional financial, legal, medical, or political advice.</Bullet>
          <Bullet>Does not represent the views of Whyrl or its developers.</Bullet>
          Always verify important information with primary sources before acting on it.
        </Section>

        <Section title="6. Copyright and Content">
          The Whyrl application, its design, branding, and AI-generated summaries are the intellectual property of Whyrl's developers. Underlying news headlines are sourced from NewsAPI and Reddit under their respective terms of service. We do not claim ownership of third-party source content.{'\n\n'}You may not reproduce, redistribute, or commercially exploit Whyrl's content without written permission.
        </Section>

        <Section title="7. Acceptable Use">
          You agree not to:
          <Bullet>Use Whyrl for any unlawful purpose.</Bullet>
          <Bullet>Attempt to reverse-engineer or scrape the application or its API.</Bullet>
          <Bullet>Interfere with the operation of our servers or services.</Bullet>
          <Bullet>Use automated means to access Whyrl without our express permission.</Bullet>
        </Section>

        <Section title="8. Advertising">
          Free-tier users will see advertisements served by Google AdMob. By using the free tier, you consent to the display of ads. Premium subscribers are ad-free. We are not responsible for the content of third-party advertisements.
        </Section>

        <Section title="9. Limitation of Liability">
          To the maximum extent permitted by Canadian law, Whyrl and its developers shall not be liable for any indirect, incidental, or consequential damages arising from your use of the app, including reliance on AI-generated summaries. Our total liability shall not exceed the amount you paid for the service in the 12 months preceding any claim.
        </Section>

        <Section title="10. Modifications to the Service">
          We reserve the right to modify or discontinue Whyrl at any time, with or without notice. We will make reasonable efforts to notify users of significant changes via in-app notice.
        </Section>

        <Section title="11. Changes to These Terms">
          We may update these terms periodically. Material changes will be communicated via in-app notice. Continued use of Whyrl after changes are posted constitutes acceptance.
        </Section>

        <Section title="12. Contact">
          For questions about these terms: support@whyrl.app
        </Section>
      </ScrollView>
    </SafeAreaView>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <View style={styles.section}>
      <Text style={styles.sectionTitle}>{title}</Text>
      <Text style={styles.sectionBody}>{children}</Text>
    </View>
  );
}

function Bullet({ children }: { children: React.ReactNode }) {
  return <Text style={styles.bullet}>{'• '}{children}{'\n'}</Text>;
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: theme.colors.bg },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.surfaceBorder,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    color: theme.colors.textPrimary,
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  content: {
    padding: 20,
    paddingBottom: 60,
    maxWidth: 680,
    alignSelf: 'center',
    width: '100%',
  },
  updated: {
    color: theme.colors.textMuted,
    fontSize: 12,
    marginBottom: 24,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    color: theme.colors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 8,
  },
  sectionBody: {
    color: theme.colors.textSecondary,
    fontSize: 14,
    lineHeight: 22,
  },
  bullet: {
    color: theme.colors.textSecondary,
    fontSize: 14,
    lineHeight: 22,
  },
});
